/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current authenticated user
         * @description Returns the tenant-scoped platform user for the authenticated session (JWT `sub` resolved against the `users` table). This is profile data only — not the enriched authorization principal; use GET /auth/principal for that.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user for this tenant. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Request validation error (including tenant header/JWT mismatch when header is provided). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description User not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/principal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get enriched principal for authorization
         * @description Returns the exact `PrincipalService.getPrincipal` payload attached by PEP as `request.cerbosPrincipal` (no recomputation). Semantically this matches the Cerbos principal used on checks: `id` is `principal.id`, `roles` is `principal.roles`, and `attributes` is `principal.attr` (same snake_case keys as `principalAttrsForCerbos` in `@hims/ts-sdk-authz`). The HTTP body nests attrs under `attributes` (Cerbos uses `attr`). Session-only JWT fields (`sessionId`, `iat`, `exp`, `iss`, …) are not included here — use the identity layer / token for those. If enrichment did not run, the service responds with 500 `CERBOS_PRINCIPAL_UNAVAILABLE`.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Enriched principal (JWT claims plus resolved authorization data; token not included). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Principal"];
                    };
                };
                /** @description Invalid request (e.g. principal resolution failed). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Platform user not found for this tenant (enrichment failed). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Enriched principal missing on the request (PEP mis-configuration) or other server fault. Code `CERBOS_PRINCIPAL_UNAVAILABLE` when principal enrichment did not run before this route. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenant-scoped platform users (ABAC-filtered)
         * @description Returns users for the active tenant. Route access is gated on `user.list` (PEP); the list body is filtered using a single Cerbos PlanResources call for `user.read` and the returned query-plan AST (evaluated locally against each row), not per-row CheckResources.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Users visible to the caller under Cerbos ABAC rules for this tenant. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
                /** @description Request validation error (including tenant header/JWT mismatch when header is provided). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a tenant-scoped platform user record
         * @description Creates a row in the platform `users` table for the current tenant (`iq_tenant_id` is the Citus distribution key and is taken from request context, not the request body). Credential storage and synthetic identity anchors remain in better-auth (`ba_*`) and are out of scope for this request body.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Display name for the principal (required platform profile field). */
                        full_name: string;
                        /** @description Business contact email (nullable, non-unique per tenant); not the better-auth synthetic anchor. */
                        email?: string | null;
                        /** @description Business contact phone. */
                        phone?: string | null;
                        /** @description Optional login handle; unique per tenant when set. */
                        username?: string | null;
                        /**
                         * Format: uuid
                         * @description Organization scope (configurator organizations.id); logical reference only.
                         */
                        org_id?: string | null;
                        /** @description Department for ABAC enrichment when stored on the profile. */
                        department?: string | null;
                        /** @description Initial minimum clearance tier required to access this user record (ABAC). */
                        clearance_tier_required?: number;
                    };
                };
            };
            responses: {
                /** @description Platform user created for the tenant. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Invalid input (e.g. malformed body or invalid field values). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tenant-scoped user by id */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Platform user id within the current tenant. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User found. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Request validation error (including tenant header/JWT mismatch when header is provided). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description User not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a tenant-scoped user */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Platform user id within the current tenant. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Display name for the principal. */
                        full_name?: string;
                        /** @description Business contact email (nullable, non-unique per tenant); not the better-auth synthetic anchor. */
                        email?: string | null;
                        /** @description Business contact phone. */
                        phone?: string | null;
                        /** @description Optional login handle; unique per tenant when set. */
                        username?: string | null;
                        /**
                         * Format: uuid
                         * @description Organization scope (configurator organizations.id); logical reference only.
                         */
                        org_id?: string | null;
                        /** @description Department for ABAC when updated on the profile. */
                        department?: string | null;
                        /** @description Minimum clearance tier for sensitive access (ABAC). */
                        clearance_tier_required?: number;
                        /**
                         * @description Platform user lifecycle state.
                         * @enum {string}
                         */
                        status?: "active" | "inactive" | "suspended";
                        /**
                         * Format: uuid
                         * @description External identity anchor (e.g. better-auth user id) when linked.
                         */
                        auth_user_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description User updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Invalid input (e.g. malformed body or invalid field values). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description User not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/role-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign a role to a user
         * @description Creates a row in `role_assignments` for the current tenant. `iq_tenant_id` is taken from request context, not the request body.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Platform user id within the current tenant.
                         */
                        user_id: string;
                        /**
                         * Format: uuid
                         * @description Role id within the current tenant.
                         */
                        role_id: string;
                    };
                };
            };
            responses: {
                /** @description Role assignment created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoleAssignment"];
                    };
                };
                /** @description Malformed request (e.g. invalid JSON, missing required fields, or invalid UUID format). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description User or role not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Duplicate role assignment (user already has this role for this tenant under the same scope). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorMessage: {
            /** @description Machine-readable error code. */
            code: string;
            message: string;
            /** @description Request correlation identifier. */
            correlation_id?: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            full_name: string;
            /** @description Business contact email when stored. */
            email?: string | null;
            /** @description Business contact phone when stored. */
            phone?: string | null;
            /**
             * Format: uuid
             * @description External identity anchor when linked.
             */
            auth_user_id?: string | null;
            /** @description Login handle when set. */
            username?: string | null;
            /**
             * Format: uuid
             * @description Organization scope when set.
             */
            org_id?: string | null;
            /** @description Department attribute for ABAC (persisted profile field). */
            department?: string | null;
            /** @description Minimum principal clearance tier (from Cerbos `um_clearance_effective_tier`) required for user.read / user.update / user.delete on this record. 0 = standard. */
            clearance_tier_required?: number;
            /**
             * @description Platform user lifecycle state.
             * @enum {string}
             */
            status: "active" | "inactive" | "suspended";
        };
        /** @description Authorization snapshot for PDP alignment. Maps to Cerbos principal as `{ id, roles, attr: attributes }` after `request.user` is synced from this payload in the enrichment hook (see `@hims/user-management` principal enrichment plugin). */
        Principal: {
            /** @description Same value as Cerbos `principal.id` and JWT `sub` (platform user id). */
            id: string;
            roles: string[];
            attributes: {
                iq_tenant_id: string;
                department: string | null;
                org_id: string | null;
                capabilities: string[];
                delegated_capabilities: string[];
                /** @description Map of clearance types to levels (e.g. psychiatric, vip). */
                clearances: {
                    [key: string]: string;
                };
                /** @description Highest clearance tier derived from `clearances` for comparison with `resource.attr.required_clearance` on user resources in Cerbos. */
                um_clearance_effective_tier: number;
            };
        };
        RoleAssignment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            role_id: string;
        };
    };
    responses: never;
    parameters: {
        /**
         * @deprecated
         * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
         */
        IqTenantIdHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
