/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current authenticated user
         * @description Returns the tenant-scoped platform user for the authenticated session (JWT `sub` resolved against the `users` table). This is profile data only — not the enriched authorization principal; use GET /auth/principal for that.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user for this tenant. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Request validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description User not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/principal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get enriched principal for authorization
         * @description Returns the exact `PrincipalService.getPrincipal` payload attached by PEP as `request.cerbosPrincipal` (no recomputation). Semantically this matches the Cerbos principal used on checks: `id` is `principal.id`, `roles` is `principal.roles`, and `attributes` is `principal.attr` (same snake_case keys as `principalAttrsForCerbos` in `@hims/ts-sdk-authz`). The HTTP body nests attrs under `attributes` (Cerbos uses `attr`). Session-only JWT fields (`sessionId`, `iat`, `exp`, `iss`, …) are not included here — use the identity layer / token for those. If enrichment did not run, the service responds with 500 `CERBOS_PRINCIPAL_UNAVAILABLE`.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Enriched principal (JWT claims plus resolved authorization data; token not included). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Principal"];
                    };
                };
                /** @description Invalid request (e.g. principal resolution failed). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description Platform user not found for this tenant (enrichment failed). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Enriched principal missing on the request (PEP mis-configuration) or other server fault. Code `CERBOS_PRINCIPAL_UNAVAILABLE` when principal enrichment did not run before this route. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List full runtime capability catalog
         * @description Returns the full global **runtime capability** catalog (not Master Data permissions). Each row's `module` field is a **module slug** aligned with `master_data.modules.slug`. For tenant-scoped role editors, prefer `GET /capabilities/assignable`.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Global capability catalog used for role composition. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Capability"][];
                    };
                };
                /** @description Request validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/assignable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List assignable runtime capabilities for tenant roles
         * @description Returns active **runtime capabilities** from the UM catalog, filtered to **module slugs** enabled for the tenant (`configurator.tenant_modules` resolved via `master_data.modules.slug`) plus platform runtime modules (`user-management`, `configurator`). This is not a Master Data permissions API. Fails closed when tenant module entitlement or module catalog lookup fails.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tenant-scoped assignable runtime capability catalog for role composition. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Capability"][];
                    };
                };
                /** @description Request validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                500: components["responses"]["InternalError"];
                /** @description Configurator tenant module entitlement or Master Data module catalog lookup failed. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a canonical capability by id
         * @description Returns a single capability from the global capability catalog. Capabilities remain the canonical authorization primitives and are not tenant-scoped.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Canonical capability id from the global capability catalog. */
                    id: components["parameters"]["CapabilityIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Capability found in the canonical catalog. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Capability"];
                    };
                };
                /** @description Request validation error (including malformed capability id). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description Capability not found in the catalog. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenant-scoped roles */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Roles defined for the active tenant. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Role"][];
                    };
                };
                /** @description Request validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /** Create a tenant-scoped role */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Canonical tenant-scoped role code (unique per tenant). */
                        code: string;
                        /** @description Role type from master-data role-types picklist; many roles may share the same type. */
                        role_type: string;
                        /** @description Human-readable role label. */
                        display_name: string;
                        description?: string | null;
                        /** @description System-managed role flag. */
                        is_system?: boolean;
                        /** @enum {string} */
                        status?: "active" | "inactive";
                    };
                };
            };
            responses: {
                /** @description Role created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Role"];
                    };
                };
                /** @description Invalid input. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description Duplicate role code in this tenant. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tenant-scoped role by id */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Tenant-scoped role id. */
                    id: components["parameters"]["RoleIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Role found. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Role"];
                    };
                };
                /** @description Request validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description Role not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a tenant-scoped role */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Tenant-scoped role id. */
                    id: components["parameters"]["RoleIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted role. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Role"];
                    };
                };
                /** @description Request validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description Role not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Role template still has active user associations and cannot be deleted. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        /** Update a tenant-scoped role */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Tenant-scoped role id. */
                    id: components["parameters"]["RoleIdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        code?: string;
                        /** @description Role type from master-data role-types picklist. */
                        role_type?: string;
                        display_name?: string;
                        description?: string | null;
                        is_system?: boolean;
                        /** @enum {string} */
                        status?: "active" | "inactive";
                    };
                };
            };
            responses: {
                /** @description Role updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Role"];
                    };
                };
                /** @description Invalid input. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description Role not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Duplicate role code in this tenant. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        trace?: never;
    };
    "/roles/{id}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List capabilities composed into a role */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Tenant-scoped role id. */
                    id: components["parameters"]["RoleIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Capabilities currently composed into the role. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Capability"][];
                    };
                };
                /** @description Request validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description Role not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        /** Replace the capabilities composed into a role */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Tenant-scoped role id. */
                    id: components["parameters"]["RoleIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Canonical capability ids to compose into the role. */
                        capability_ids: string[];
                    };
                };
            };
            responses: {
                /** @description Updated role composition. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Capability"][];
                    };
                };
                /** @description Invalid input. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description Role or capability not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenant-scoped platform users (ABAC-filtered)
         * @description Returns users for the active tenant. Route access is gated on `user.list` (PEP); the list body is filtered using a single Cerbos PlanResources call for `user.read` and the returned query-plan AST (evaluated locally against each row), not per-row CheckResources.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Users visible to the caller under Cerbos ABAC rules for this tenant. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
                /** @description Request validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Create a tenant-scoped user with login access
         * @description Creates the tenant-scoped platform `users` row for the current tenant (`iq_tenant_id` is the Citus distribution key and is taken from request context, not the request body), provisions the linked better-auth login account for the same principal, and optionally writes direct user capabilities from `capability_ids` plus copied template access from `role_template_ids`. When `role_template_capability_ids` is present, exactly one role id must be listed in `role_template_ids`, and only those capabilities (each belonging to that role) are granted with source `role_template`; omit the field to copy the full role composition.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Display name for the principal (required platform profile field). */
                        full_name: string;
                        /**
                         * Format: email
                         * @description Login email used to provision the current minimal better-auth account and retained as business contact email.
                         */
                        email: string;
                        /** @description Initial login password for the linked better-auth account. */
                        password: string;
                        /** @description Business contact phone. */
                        phone?: string | null;
                        /** @description Optional login handle; unique per tenant when set. */
                        username?: string | null;
                        /**
                         * Format: uuid
                         * @description Organization scope (configurator organizations.id); logical reference only.
                         */
                        org_id?: string | null;
                        /** @description Department for ABAC enrichment when stored on the profile. */
                        department?: string | null;
                        /** @description Initial minimum clearance tier required to access this user record (ABAC). */
                        clearance_tier_required?: number;
                        /** @description Direct user capability ids to persist immediately after the user is created. */
                        capability_ids?: string[];
                        /** @description Optional role-template ids to apply immediately after the user is created. */
                        role_template_ids?: string[];
                        /** @description Optional subset of capability ids to grant from the role template(s). When this array is present, `role_template_ids` must contain exactly one id, and every entry must be a capability currently assigned to that role. Omit to grant the full capability set defined on each role template. */
                        role_template_capability_ids?: string[];
                    };
                };
            };
            responses: {
                /** @description Platform user and linked login account created for the tenant. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Invalid input (e.g. malformed body or invalid field values). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tenant-scoped user by id */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Platform user id within the current tenant. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User found. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Request validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description User not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a tenant-scoped user */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Platform user id within the current tenant. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Display name for the principal. */
                        full_name?: string;
                        /** @description Business contact email (nullable, non-unique per tenant); not the better-auth synthetic anchor. */
                        email?: string | null;
                        /** @description Business contact phone. */
                        phone?: string | null;
                        /** @description Optional login handle; unique per tenant when set. */
                        username?: string | null;
                        /**
                         * Format: uuid
                         * @description Organization scope (configurator organizations.id); logical reference only.
                         */
                        org_id?: string | null;
                        /** @description Department for ABAC when updated on the profile. */
                        department?: string | null;
                        /** @description Minimum clearance tier for sensitive access (ABAC). */
                        clearance_tier_required?: number;
                        /**
                         * @description Platform user lifecycle state.
                         * @enum {string}
                         */
                        status?: "active" | "inactive" | "suspended";
                        /**
                         * Format: uuid
                         * @description External identity anchor (e.g. better-auth user id) when linked.
                         */
                        auth_user_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description User updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Invalid input (e.g. malformed body or invalid field values). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description User not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        trace?: never;
    };
    "/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List applied role templates for a tenant-scoped user
         * @description Returns the role templates applied to the specified user (`user_roles` associations). Runtime authorization resolves from active rows in `user_capabilities` (snapshot grants). See ADR-0031 for snapshot semantics; PEP may temporarily union live template capabilities until issue #60.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Platform user id within the current tenant. */
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Role templates currently associated with the user within the active tenant. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppliedRoleTemplate"][];
                    };
                };
                /** @description Request validation error (including malformed user id). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description User not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Apply a role template to a user
         * @description Creates or updates a `user_roles` association and synchronizes the role-scoped capability snapshot in `user_capabilities` during the same write flow. Re-applying the same template narrows or widens the copied grants for that `source_role_id`. When `role_template_capability_ids` is present, only those capabilities (each belonging to the role) are included in the snapshot; omit the field to use the role's full composition. Later edits to the role template definition do not retroactively change existing user rows.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Platform user id within the current tenant. */
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Role-template id within the current tenant.
                         */
                        role_id: string;
                        /** @description Optional subset of capability ids to grant from this role template. Each entry must be a capability currently assigned to the role. Omit to synchronize the full capability set defined on the role template. */
                        role_template_capability_ids?: string[];
                    };
                };
            };
            responses: {
                /** @description Role template applied and capability snapshot synchronized. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppliedRoleTemplate"];
                    };
                };
                /** @description Malformed request body or invalid UUID fields. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description User or role template not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description This role template is already applied to the user. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a role-template association from a user
         * @description Removes the `user_roles` association and soft-revokes active `user_capabilities` rows where `grant_source` is `role_template` and `source_role_id` matches the detached role. Manual, delegated, and system grants are not changed. Revoked rows retain audit fields (`revoked_at`, `revoked_by_user_id`).
         */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Platform user id within the current tenant. */
                    id: components["parameters"]["UserIdPath"];
                    /** @description Role-template id within the current tenant. */
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Role-template association removed and matching role-scoped capability snapshot revoked. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AppliedRoleTemplate"];
                    };
                };
                /** @description Invalid or missing path parameters. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description User, role template, or user-role association not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get persisted user capability grants
         * @description Returns the user's persisted base grants split into direct grants, copied template grants, and applied role-template associations. Delegated overlays are excluded from this endpoint.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Platform user id within the current tenant. */
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Persisted user capability grants plus applied role-template associations. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserCapabilitiesSnapshot"];
                    };
                };
                /** @description Request validation error (including malformed user id). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description User not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        /**
         * Replace direct user capability grants
         * @description Replaces the user's direct manual capability grants. Copied template grants remain untouched until an explicit capability edit changes them.
         */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Platform user id within the current tenant. */
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        capability_ids: string[];
                    };
                };
            };
            responses: {
                /** @description Direct user grants replaced; response returns the refreshed persisted grant snapshot. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserCapabilitiesSnapshot"];
                    };
                };
                /** @description Invalid input (e.g. malformed body or invalid UUID format). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description User or capability not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/effective-capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get effective runtime capabilities for a user
         * @description Returns the runtime-effective capability keys for Cerbos principal enrichment. Primary source is active `user_capabilities` snapshot rows; delegated overlays and clearances are included. Until issue #60, implementation may temporarily union live `user_roles` join `role_capabilities` for active associations (hybrid PEP — see ADR-0031).
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Platform user id within the current tenant. */
                    id: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Effective runtime authorization snapshot for the specified user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserEffectiveCapabilities"];
                    };
                };
                /** @description Request validation error (including malformed user id). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description User not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate a tenant-scoped platform user
         * @description Soft-deactivates the user by setting `status` to `inactive`. Idempotent when already inactive. Uses Cerbos action `user.deactivate` (not `user.update`) so policies can separate profile edits from deactivation.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @deprecated
                     * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
                     */
                    iq_tenant_id?: components["parameters"]["IqTenantIdHeader"];
                };
                path: {
                    /** @description Platform user id within the current tenant. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User is now inactive (or was already inactive). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Request validation error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                /** @description Missing or invalid bearer token. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description User not found for this tenant. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorMessage"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Capability: {
            /** Format: uuid */
            id: string;
            /** @description Runtime Cerbos vocabulary key (e.g. `um:user:read`). Stable once granted; distinct from Master Data `permissions.slug`. */
            capability_key: string;
            /** @description Module slug — MUST equal `master_data.modules.slug` (kebab-case, e.g. `user-management`, `opd`, `billing`). */
            module: string;
            feature: string;
            action: string;
            display_name: string;
            description?: string | null;
            is_active: boolean;
            /** @description Future catalog sync — originating Master Data module slug when this runtime capability was imported (nullable until sync exists). */
            source_module_slug?: string | null;
            /** @description Future catalog sync — originating Master Data `permissions.slug` (nullable until sync exists). */
            source_permission_slug?: string | null;
            /** @description Future catalog sync — system of record for provenance metadata. */
            source_catalog?: "master_data" | null;
        };
        Role: {
            /** Format: uuid */
            id: string;
            /** @description Tenant-unique short identifier. */
            code: string;
            /** @description Role type from master-data role-types picklist (not unique per tenant). */
            role_type: string;
            display_name: string;
            description?: string | null;
            is_system: boolean;
            /** @enum {string} */
            status: "active" | "inactive";
        };
        AppliedRoleTemplate: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            role_id: string;
            /** Format: uuid */
            assigned_by_user_id: string | null;
            /** Format: date-time */
            assigned_at: string;
            role: components["schemas"]["Role"];
        };
        UserCapabilityGrant: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            capability_id: string;
            capability_key: string;
            module: string;
            feature: string;
            action: string;
            display_name: string;
            description?: string | null;
            /** @enum {string} */
            grant_source: "manual" | "role_template" | "delegated" | "system";
            /** Format: uuid */
            source_role_id: string | null;
            /** Format: uuid */
            granted_by_user_id: string | null;
            /** Format: date-time */
            granted_at: string;
            /** Format: date-time */
            revoked_at: string | null;
            /** Format: uuid */
            revoked_by_user_id: string | null;
        };
        UserCapabilitiesSnapshot: {
            direct_grants: components["schemas"]["UserCapabilityGrant"][];
            copied_grants: components["schemas"]["UserCapabilityGrant"][];
            role_templates: components["schemas"]["AppliedRoleTemplate"][];
        };
        UserEffectiveCapabilities: {
            capability_keys: string[];
            delegated_capability_keys: string[];
            clearances: {
                [key: string]: string;
            };
            um_clearance_effective_tier: number;
        };
        ErrorMessage: {
            /** @description Machine-readable error code. */
            code: string;
            message: string;
            /** @description Request correlation identifier. */
            correlation_id?: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            full_name: string;
            /** @description Business contact email when stored. */
            email?: string | null;
            /** @description Business contact phone when stored. */
            phone?: string | null;
            /**
             * Format: uuid
             * @description External identity anchor when linked.
             */
            auth_user_id?: string | null;
            /** @description Login handle when set. */
            username?: string | null;
            /**
             * Format: uuid
             * @description Organization scope when set.
             */
            org_id?: string | null;
            /** @description Department attribute for ABAC (persisted profile field). */
            department?: string | null;
            /** @description Minimum principal clearance tier (from Cerbos `um_clearance_effective_tier`) required for user.read / user.update / user.deactivate on this record. 0 = standard. */
            clearance_tier_required?: number;
            /**
             * @description Platform user lifecycle state.
             * @enum {string}
             */
            status: "active" | "inactive" | "suspended";
        };
        /** @description Authorization snapshot for PDP alignment. Maps to Cerbos principal as `{ id, roles, attr: attributes }` after `request.user` is synced from this payload in the enrichment hook (see `@hims/user-management` principal enrichment plugin). */
        Principal: {
            /** @description Same value as Cerbos `principal.id` and JWT `sub` (platform user id). */
            id: string;
            roles: string[];
            attributes: {
                iq_tenant_id: string;
                department: string | null;
                org_id: string | null;
                capabilities: string[];
                delegated_capabilities: string[];
                /** @description Map of clearance types to levels (e.g. psychiatric, vip). */
                clearances: {
                    [key: string]: string;
                };
                /** @description Highest clearance tier derived from `clearances` for comparison with `resource.attr.required_clearance` on user resources in Cerbos. */
                um_clearance_effective_tier: number;
            };
        };
    };
    responses: {
        /** @description Authorization denied — Cerbos PDP rejection (PEP) or tenant context mismatch (`TENANT_CONTEXT_MISMATCH` when optional `iq_tenant_id` header does not match the JWT tenant claim). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorMessage"];
            };
        };
        /** @description Unexpected server failure while processing the request. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorMessage"];
            };
        };
    };
    parameters: {
        /**
         * @deprecated
         * @description Optional diagnostic header. Canonical tenant scope is JWT `iq_tenant_id`. If this header is supplied, runtime requires exact match with JWT tenant scope.
         */
        IqTenantIdHeader: string;
        /** @description Canonical capability id from the global capability catalog. */
        CapabilityIdPath: string;
        /** @description Tenant-scoped role id. */
        RoleIdPath: string;
        /** @description Platform user id within the current tenant. */
        UserIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
