server:
  httpListenAddr: ':3592'
  grpcListenAddr: ':3593'
  cors:
    allowedOrigins:
      - http://localhost:5173
      - http://localhost:5174
    allowedHeaders:
      - content-type
      - authorization

storage:
  driver: disk
  disk:
    directory: /policies
    watchForChanges: true

schema:
  enforcement: warn

audit:
  enabled: true
  backend: local
  local:
    storagePath: /tmp/cerbos-audit
    retentionPeriod: 168h
