"""Align catalog indexes/constraints with the models (autogenerate-derived).

The 0001 baseline froze index shapes the models have since moved past: the tenant
unique partial indexes were renamed to the ``*_active_key`` convention (same columns
and ``WHERE NOT is_deleted`` — enforcement preserved, not added),
``uq_picklist_values_category_value`` became a real UNIQUE constraint instead of a
unique index, and a set of small support indexes the models never declare
(``idx_*``/``tm_idx_*``/display-order composites, plus the superseded
``diagnoses_tenant_id_icd10_code_icd_version_idx``) are dropped — small reference
catalogs, models are the single source of truth.

Generated by alembic autogenerate against a fully-migrated DB (env.py scopes
autogenerate to the module schemas and prunes functional-index reflection noise),
then hand-reviewed. With this applied, ``alembic check`` is clean and runs in
scripts/run-integration-tests.sh as the drift gate that would have caught the
missing inventory migration (0003) the day it happened.

Revision ID: 0004_catalog_index_alignment
Revises: 0003_inventory_masters
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0004_catalog_index_alignment'
down_revision: str | Sequence[str] | None = '0003_inventory_masters'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_departments_is_deleted'), table_name='departments', schema='master_global')
    op.drop_index(op.f('idx_departments_type'), table_name='departments', schema='master_global')
    op.drop_index(op.f('idx_module_permissions_module'), table_name='module_permissions', schema='master_global')
    op.drop_index(op.f('idx_module_permissions_permission'), table_name='module_permissions', schema='master_global')
    op.drop_index(op.f('idx_modules_category'), table_name='modules', schema='master_global')
    op.drop_index(op.f('idx_modules_is_deleted'), table_name='modules', schema='master_global')
    op.drop_index(op.f('idx_modules_parent'), table_name='modules', schema='master_global')
    op.drop_index(op.f('uq_picklist_values_category_value'), table_name='picklist_values', schema='master_global')
    op.create_unique_constraint('uq_picklist_values_category_value', 'picklist_values', ['category_id', 'value'], schema='master_global')
    op.drop_index(op.f('ix_visitpad_unit_conversions_order'), table_name='unit_conversions', schema='master_global')
    op.drop_index(op.f('ix_visitpad_units_display_order'), table_name='units', schema='master_global')
    op.drop_index(op.f('allergens_tenant_id_code_idx'), table_name='allergens', schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index('allergens_tenant_code_active_key', 'allergens', ['iq_tenant_id', 'code'], unique=True, schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index(op.f('allergy_reactions_tenant_id_code_idx'), table_name='allergy_reactions', schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index('allergy_reactions_tenant_code_active_key', 'allergy_reactions', ['iq_tenant_id', 'code'], unique=True, schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index(op.f('chief_complaints_tenant_id_code_idx'), table_name='chief_complaints', schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index('chief_complaints_tenant_code_active_key', 'chief_complaints', ['iq_tenant_id', 'code'], unique=True, schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index(op.f('chronic_illnesses_tenant_id_icd10_code_idx'), table_name='chronic_illnesses', schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index('chronic_illnesses_tenant_icd_active_key', 'chronic_illnesses', ['iq_tenant_id', 'icd10_code'], unique=True, schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index(op.f('tm_idx_departments_iq_tenant_id'), table_name='departments', schema='master_tenant')
    op.drop_index(op.f('tm_idx_departments_is_deleted'), table_name='departments', schema='master_tenant')
    op.drop_index(op.f('tm_idx_departments_type'), table_name='departments', schema='master_tenant')
    op.drop_index(op.f('diagnoses_tenant_id_icd10_code_icd_version_idx'), table_name='diagnoses', schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.drop_index(op.f('medicines_tenant_id_code_idx'), table_name='medicines', schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index('medicines_tenant_code_active_key', 'medicines', ['iq_tenant_id', 'code'], unique=True, schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index(op.f('tm_idx_module_permissions_module'), table_name='module_permissions', schema='master_tenant')
    op.drop_index(op.f('tm_idx_module_permissions_permission'), table_name='module_permissions', schema='master_tenant')
    op.drop_index(op.f('tm_idx_modules_category'), table_name='modules', schema='master_tenant')
    op.drop_index(op.f('tm_idx_modules_is_deleted'), table_name='modules', schema='master_tenant')
    op.drop_index(op.f('tm_idx_modules_parent'), table_name='modules', schema='master_tenant')
    op.drop_index(op.f('procedures_tenant_id_cpt_code_idx'), table_name='procedures', schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index('procedures_tenant_cpt_active_key', 'procedures', ['iq_tenant_id', 'cpt_code'], unique=True, schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index(op.f('rx_columns_tenant_id_section_code_idx'), table_name='rx_columns', schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index('rx_columns_tenant_section_code_active_key', 'rx_columns', ['iq_tenant_id', 'section', 'code'], unique=True, schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index(op.f('unit_conversions_tenant_id_display_order_from_unit_code_idx'), table_name='unit_conversions', schema='master_tenant')
    op.drop_index(op.f('unit_conversions_tenant_id_from_unit_code_to_unit_code_idx'), table_name='unit_conversions', schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index('unit_conversions_tenant_from_to_active_key', 'unit_conversions', ['iq_tenant_id', 'from_unit_code', 'to_unit_code'], unique=True, schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index(op.f('units_tenant_id_code_idx'), table_name='units', schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.drop_index(op.f('units_tenant_id_display_order_code_idx'), table_name='units', schema='master_tenant')
    op.create_index('units_tenant_code_active_key', 'units', ['iq_tenant_id', 'code'], unique=True, schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index(op.f('vitals_tenant_id_code_idx'), table_name='vitals', schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index('vitals_tenant_code_active_key', 'vitals', ['iq_tenant_id', 'code'], unique=True, schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('vitals_tenant_code_active_key', table_name='vitals', schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('vitals_tenant_id_code_idx'), 'vitals', ['iq_tenant_id', 'code'], unique=True, schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.drop_index('units_tenant_code_active_key', table_name='units', schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('units_tenant_id_display_order_code_idx'), 'units', ['iq_tenant_id', 'display_order', 'code'], unique=False, schema='master_tenant')
    op.create_index(op.f('units_tenant_id_code_idx'), 'units', ['iq_tenant_id', 'code'], unique=True, schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.drop_index('unit_conversions_tenant_from_to_active_key', table_name='unit_conversions', schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('unit_conversions_tenant_id_from_unit_code_to_unit_code_idx'), 'unit_conversions', ['iq_tenant_id', 'from_unit_code', 'to_unit_code'], unique=True, schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index(op.f('unit_conversions_tenant_id_display_order_from_unit_code_idx'), 'unit_conversions', ['iq_tenant_id', 'display_order', 'from_unit_code'], unique=False, schema='master_tenant')
    op.drop_index('rx_columns_tenant_section_code_active_key', table_name='rx_columns', schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('rx_columns_tenant_id_section_code_idx'), 'rx_columns', ['iq_tenant_id', 'section', 'code'], unique=True, schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.drop_index('procedures_tenant_cpt_active_key', table_name='procedures', schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('procedures_tenant_id_cpt_code_idx'), 'procedures', ['iq_tenant_id', 'cpt_code'], unique=True, schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index(op.f('tm_idx_modules_parent'), 'modules', ['parent_id'], unique=False, schema='master_tenant')
    op.create_index(op.f('tm_idx_modules_is_deleted'), 'modules', ['is_deleted'], unique=False, schema='master_tenant')
    op.create_index(op.f('tm_idx_modules_category'), 'modules', ['category'], unique=False, schema='master_tenant')
    op.create_index(op.f('tm_idx_module_permissions_permission'), 'module_permissions', ['permission_id'], unique=False, schema='master_tenant')
    op.create_index(op.f('tm_idx_module_permissions_module'), 'module_permissions', ['module_id'], unique=False, schema='master_tenant')
    op.drop_index('medicines_tenant_code_active_key', table_name='medicines', schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('medicines_tenant_id_code_idx'), 'medicines', ['iq_tenant_id', 'code'], unique=True, schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index(op.f('diagnoses_tenant_id_icd10_code_icd_version_idx'), 'diagnoses', ['iq_tenant_id', 'icd10_code', 'icd_version'], unique=True, schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index(op.f('tm_idx_departments_type'), 'departments', ['type'], unique=False, schema='master_tenant')
    op.create_index(op.f('tm_idx_departments_is_deleted'), 'departments', ['is_deleted'], unique=False, schema='master_tenant')
    op.create_index(op.f('tm_idx_departments_iq_tenant_id'), 'departments', ['iq_tenant_id'], unique=False, schema='master_tenant')
    op.drop_index('chronic_illnesses_tenant_icd_active_key', table_name='chronic_illnesses', schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('chronic_illnesses_tenant_id_icd10_code_idx'), 'chronic_illnesses', ['iq_tenant_id', 'icd10_code'], unique=True, schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.drop_index('chief_complaints_tenant_code_active_key', table_name='chief_complaints', schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('chief_complaints_tenant_id_code_idx'), 'chief_complaints', ['iq_tenant_id', 'code'], unique=True, schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.drop_index('allergy_reactions_tenant_code_active_key', table_name='allergy_reactions', schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('allergy_reactions_tenant_id_code_idx'), 'allergy_reactions', ['iq_tenant_id', 'code'], unique=True, schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.drop_index('allergens_tenant_code_active_key', table_name='allergens', schema='master_tenant', postgresql_where=sa.text('NOT is_deleted'))
    op.create_index(op.f('allergens_tenant_id_code_idx'), 'allergens', ['iq_tenant_id', 'code'], unique=True, schema='master_tenant', postgresql_where='(NOT is_deleted)')
    op.create_index(op.f('ix_visitpad_units_display_order'), 'units', ['display_order', 'code'], unique=False, schema='master_global')
    op.create_index(op.f('ix_visitpad_unit_conversions_order'), 'unit_conversions', ['display_order', 'from_unit_code'], unique=False, schema='master_global')
    op.drop_constraint('uq_picklist_values_category_value', 'picklist_values', schema='master_global', type_='unique')
    op.create_index(op.f('uq_picklist_values_category_value'), 'picklist_values', ['category_id', 'value'], unique=True, schema='master_global')
    op.create_index(op.f('idx_modules_parent'), 'modules', ['parent_id'], unique=False, schema='master_global')
    op.create_index(op.f('idx_modules_is_deleted'), 'modules', ['is_deleted'], unique=False, schema='master_global')
    op.create_index(op.f('idx_modules_category'), 'modules', ['category'], unique=False, schema='master_global')
    op.create_index(op.f('idx_module_permissions_permission'), 'module_permissions', ['permission_id'], unique=False, schema='master_global')
    op.create_index(op.f('idx_module_permissions_module'), 'module_permissions', ['module_id'], unique=False, schema='master_global')
    op.create_index(op.f('idx_departments_type'), 'departments', ['type'], unique=False, schema='master_global')
    op.create_index(op.f('idx_departments_is_deleted'), 'departments', ['is_deleted'], unique=False, schema='master_global')
    # ### end Alembic commands ###
