CREATE SCHEMA "billing";
--> statement-breakpoint
CREATE TABLE "billing"."bill_items" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"iq_tenant_id" uuid NOT NULL,
	"bill_id" uuid NOT NULL,
	"service_id" uuid,
	"item_type" text DEFAULT 'SERVICE' NOT NULL,
	"item_code" text NOT NULL,
	"description" text NOT NULL,
	"quantity" numeric(10, 2) DEFAULT '1' NOT NULL,
	"unit_price" numeric(18, 4) NOT NULL,
	"gross_amount" numeric(18, 4) NOT NULL,
	"discount_percentage" numeric(7, 4) DEFAULT '0' NOT NULL,
	"discount_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"net_amount" numeric(18, 4) NOT NULL,
	"tax_percentage" numeric(7, 4) DEFAULT '0' NOT NULL,
	"tax_amount" numeric(18, 4) NOT NULL,
	"total_amount" numeric(18, 4) NOT NULL,
	"source_module" text NOT NULL,
	"source_ref" uuid,
	"performed_date" timestamp with time zone,
	"performed_by" uuid,
	"department" text,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"idempotency_key" text,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "bill_items_iq_tenant_id_id_pk" PRIMARY KEY("iq_tenant_id","id")
);
--> statement-breakpoint
CREATE TABLE "billing"."tariff_master" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"iq_tenant_id" uuid NOT NULL,
	"service_code" text NOT NULL,
	"service_name" text NOT NULL,
	"description" text,
	"provider_id" uuid,
	"department_id" uuid,
	"category" text,
	"sub_category" text,
	"tax_type" text,
	"base_price" numeric(18, 4) NOT NULL,
	"tax_percentage" numeric(7, 4) DEFAULT '0' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"effective_from" timestamp with time zone DEFAULT now() NOT NULL,
	"effective_to" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	CONSTRAINT "tariff_master_iq_tenant_id_id_pk" PRIMARY KEY("iq_tenant_id","id")
);
--> statement-breakpoint
CREATE TABLE "billing"."bills" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"iq_tenant_id" uuid NOT NULL,
	"bill_number" text NOT NULL,
	"patient_id" uuid NOT NULL,
	"visit_id" uuid,
	"visit_type" text,
	"bill_type" text DEFAULT 'STANDALONE' NOT NULL,
	"bill_date" date DEFAULT now() NOT NULL,
	"subtotal" numeric(18, 4) DEFAULT '0' NOT NULL,
	"discount_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"discount_reason" text,
	"tax_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"total_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"round_off_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"net_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"paid_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"outstanding_amount" numeric(18, 4) DEFAULT '0' NOT NULL,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"tax_breakup" jsonb,
	"notes" text,
	"cancellation_reason" text,
	"created_by" uuid,
	"approved_by" uuid,
	"cancelled_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"approved_at" timestamp with time zone,
	"cancelled_at" timestamp with time zone,
	CONSTRAINT "bills_iq_tenant_id_id_pk" PRIMARY KEY("iq_tenant_id","id")
);
--> statement-breakpoint
CREATE TABLE "billing"."payments" (
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"iq_tenant_id" uuid NOT NULL,
	"payment_number" text NOT NULL,
	"receipt_number" text,
	"bill_id" uuid,
	"patient_id" uuid NOT NULL,
	"payment_date" timestamp with time zone DEFAULT now() NOT NULL,
	"amount" numeric(18, 4) NOT NULL,
	"payment_method" text NOT NULL,
	"transaction_id" text,
	"reference_number" text,
	"status" text DEFAULT 'SUCCESS' NOT NULL,
	"received_by" uuid,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payments_iq_tenant_id_id_pk" PRIMARY KEY("iq_tenant_id","id")
);
