"""Align the DB with the models (autogenerate-derived drift-gate cleanup).

Two leftovers from the 0001 baseline that the models never declared:
``ix_opd_visits_tenant_patient_updated`` has no consumer (opd.visits is only
queried by ``(iq_tenant_id, id)``), and the ``prescriptions.visit_id`` comment
predates the model's clearer wording. With this applied, ``alembic check`` is
clean and runs in scripts/run-integration-tests.sh as the drift gate.

Revision ID: 0002_model_alignment
Revises: 0001_baseline
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0002_model_alignment'
down_revision: str | Sequence[str] | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescriptions', 'visit_id',
               existing_type=sa.UUID(),
               comment='Logical ref registration.visit_id (registration module); UNIQUE 1:1 with prescription; no cross-schema FK',
               existing_comment='Logical ref registration.registration.visit_id; UNIQUE 1:1; no cross-schema FK',
               existing_nullable=False,
               schema='opd')
    op.drop_index(op.f('ix_opd_visits_tenant_patient_updated'), table_name='visits', schema='opd')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_opd_visits_tenant_patient_updated'), 'visits', ['iq_tenant_id', 'patient_id', 'updated_at'], unique=False, schema='opd')
    op.alter_column('prescriptions', 'visit_id',
               existing_type=sa.UUID(),
               comment='Logical ref registration.registration.visit_id; UNIQUE 1:1; no cross-schema FK',
               existing_comment='Logical ref registration.visit_id (registration module); UNIQUE 1:1 with prescription; no cross-schema FK',
               existing_nullable=False,
               schema='opd')
    # ### end Alembic commands ###
