import { M3_HIP_STATES, M3_HIU_STATES } from "@hims/ts-sdk-abha";

/** Canonical HIU states — indices match `M3_HIU_STATES` in ts-sdk-abha. */
export const M3Hiu = {
  CONSENT_INIT_REQUESTED: M3_HIU_STATES[0],
  AWAITING_PATIENT_APPROVAL: M3_HIU_STATES[1],
  CONSENT_GRANTED: M3_HIU_STATES[2],
  CONSENT_DENIED: M3_HIU_STATES[3],
  EXPIRED: M3_HIU_STATES[4],
  DATA_REQUESTED: M3_HIU_STATES[5],
  AWAITING_PUSH: M3_HIU_STATES[6],
  BUNDLES_RECEIVED: M3_HIU_STATES[7],
  BUNDLES_DECRYPTED: M3_HIU_STATES[8],
  RECORDS_INGESTED: M3_HIU_STATES[9],
  ACKNOWLEDGED: M3_HIU_STATES[10],
} as const;

/** Canonical HIP states — indices match `M3_HIP_STATES` in ts-sdk-abha. */
export const M3Hip = {
  CONSENT_NOTIFIED: M3_HIP_STATES[0],
  CONSENT_PERSISTED: M3_HIP_STATES[1],
  CONSENT_REVOKED: M3_HIP_STATES[2],
  AWAITING_DATA_REQUEST: M3_HIP_STATES[3],
  DATA_REQUESTED: M3_HIP_STATES[4],
  KEYS_EXCHANGED: M3_HIP_STATES[5],
  BUNDLES_FETCHED: M3_HIP_STATES[6],
  BUNDLES_ENCRYPTED: M3_HIP_STATES[7],
  BUNDLES_PUSHED: M3_HIP_STATES[8],
  ACKNOWLEDGED: M3_HIP_STATES[9],
  FAILED: M3_HIP_STATES[10],
} as const;
