---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: "master_data:visitpad"
  version: "default"
  rules:
    - actions: ["create", "update", "delete"]
      roles: ["*"]
      effect: EFFECT_ALLOW
      name: allow-admin-write-by-capability
      condition:
        match:
          expr: >-
            (
              "visitpad-master:visitpad:create" in request.principal.attr.capabilities ||
              "visitpad-templates:visitpad:create" in request.principal.attr.capabilities ||
              "visitpad-master:visitpad:create" in request.principal.attr.delegated_capabilities ||
              "visitpad-templates:visitpad:create" in request.principal.attr.delegated_capabilities
            )
    - actions: ["view"]
      roles: ["*"]
      effect: EFFECT_ALLOW
      name: allow-read-by-capability
      condition:
        match:
          expr: >-
            (
              "visitpad-master:visitpad:view" in request.principal.attr.capabilities ||
              "visitpad-templates:visitpad:view" in request.principal.attr.capabilities ||
              "visitpad-master:visitpad:view" in request.principal.attr.delegated_capabilities ||
              "visitpad-templates:visitpad:view" in request.principal.attr.delegated_capabilities
            )
