import {
  boolean,
  date,
  jsonb,
  numeric,
  pgSchema,
  primaryKey,
  text,
  timestamp,
  uuid,
  tenantColumn,
} from "@hims/ts-sdk-db";

export const BILLING_SCHEMA_NAME = "billing" as const;
export const billingSchema = pgSchema(BILLING_SCHEMA_NAME);

export const billingMaster = billingSchema.table(
  "tariff_master",
  {
    id: uuid("id").defaultRandom().notNull(),
    ...tenantColumn(),
    service_code: text("service_code").notNull(),
    service_name: text("service_name").notNull(),
    description: text("description"),
    provider_id: uuid("provider_id"),
    department_id: uuid("department_id"),
    category: text("category"),
    sub_category: text("sub_category"),
    tax_type: text("tax_type"),
    base_price: numeric("base_price", { precision: 18, scale: 4 }).notNull(),
    tax_percentage: numeric("tax_percentage", { precision: 7, scale: 4 })
      .notNull()
      .default("0"),
    is_active: boolean("is_active").notNull().default(true),
    effective_from: timestamp("effective_from", { withTimezone: true }).notNull().defaultNow(),
    effective_to: timestamp("effective_to", { withTimezone: true }),
    created_at: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updated_at: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    created_by: uuid("created_by"),
    updated_by: uuid("updated_by"),
  },
  (t) => [primaryKey({ columns: [t.iq_tenant_id, t.id] })],
);

export const bills = billingSchema.table(
  "bills",
  {
    id: uuid("id").defaultRandom().notNull(),
    ...tenantColumn(),
    bill_number: text("bill_number").notNull(),
    patient_id: uuid("patient_id").notNull(),
    visit_id: uuid("visit_id"),
    visit_type: text("visit_type"),
    bill_type: text("bill_type").notNull().default("STANDALONE"),
    bill_date: date("bill_date").notNull().defaultNow(),
    subtotal: numeric("subtotal", { precision: 18, scale: 4 }).notNull().default("0"),
    discount_amount: numeric("discount_amount", { precision: 18, scale: 4 }).notNull().default("0"),
    discount_reason: text("discount_reason"),
    tax_amount: numeric("tax_amount", { precision: 18, scale: 4 }).notNull().default("0"),
    total_amount: numeric("total_amount", { precision: 18, scale: 4 }).notNull().default("0"),
    round_off_amount: numeric("round_off_amount", { precision: 18, scale: 4 }).notNull().default("0"),
    net_amount: numeric("net_amount", { precision: 18, scale: 4 }).notNull().default("0"),
    paid_amount: numeric("paid_amount", { precision: 18, scale: 4 }).notNull().default("0"),
    outstanding_amount: numeric("outstanding_amount", { precision: 18, scale: 4 }).notNull().default("0"),
    status: text("status").notNull().default("DRAFT"),
    tax_breakup: jsonb("tax_breakup"),
    notes: text("notes"),
    cancellation_reason: text("cancellation_reason"),
    created_by: uuid("created_by"),
    approved_by: uuid("approved_by"),
    cancelled_by: uuid("cancelled_by"),
    created_at: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updated_at: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    approved_at: timestamp("approved_at", { withTimezone: true }),
    cancelled_at: timestamp("cancelled_at", { withTimezone: true }),
  },
  (t) => [primaryKey({ columns: [t.iq_tenant_id, t.id] })],
);

export const billItems = billingSchema.table(
  "bill_items",
  {
    id: uuid("id").defaultRandom().notNull(),
    ...tenantColumn(),
    bill_id: uuid("bill_id").notNull(),
    service_id: uuid("service_id"),
    item_type: text("item_type").notNull().default("SERVICE"),
    item_code: text("item_code").notNull(),
    description: text("description").notNull(),
    quantity: numeric("quantity", { precision: 10, scale: 2 }).notNull().default("1"),
    unit_price: numeric("unit_price", { precision: 18, scale: 4 }).notNull(),
    gross_amount: numeric("gross_amount", { precision: 18, scale: 4 }).notNull(),
    discount_percentage: numeric("discount_percentage", { precision: 7, scale: 4 }).notNull().default("0"),
    discount_amount: numeric("discount_amount", { precision: 18, scale: 4 }).notNull().default("0"),
    net_amount: numeric("net_amount", { precision: 18, scale: 4 }).notNull(),
    tax_percentage: numeric("tax_percentage", { precision: 7, scale: 4 }).notNull().default("0"),
    tax_amount: numeric("tax_amount", { precision: 18, scale: 4 }).notNull(),
    total_amount: numeric("total_amount", { precision: 18, scale: 4 }).notNull(),
    source_module: text("source_module").notNull(),
    source_ref: uuid("source_ref"),
    performed_date: timestamp("performed_date", { withTimezone: true }),
    performed_by: uuid("performed_by"),
    department: text("department"),
    status: text("status").notNull().default("ACTIVE"),
    idempotency_key: text("idempotency_key"),
    notes: text("notes"),
    created_at: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updated_at: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.iq_tenant_id, t.id] })],
);

export const payments = billingSchema.table(
  "payments",
  {
    id: uuid("id").defaultRandom().notNull(),
    ...tenantColumn(),
    payment_number: text("payment_number").notNull(),
    receipt_number: text("receipt_number"),
    bill_id: uuid("bill_id"),
    patient_id: uuid("patient_id").notNull(),
    payment_date: timestamp("payment_date", { withTimezone: true }).notNull().defaultNow(),
    amount: numeric("amount", { precision: 18, scale: 4 }).notNull(),
    payment_method: text("payment_method").notNull(),
    transaction_id: text("transaction_id"),
    reference_number: text("reference_number"),
    status: text("status").notNull().default("SUCCESS"),
    received_by: uuid("received_by"),
    notes: text("notes"),
    created_at: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updated_at: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.iq_tenant_id, t.id] })],
);
