import {
  DEVELOPMENT_BOOTSTRAP_ROLE_CODE,
  DEVELOPMENT_BOOTSTRAP_ROLE_ID,
  DEVELOPMENT_BOOTSTRAP_USER_EMAIL,
  DEVELOPMENT_BOOTSTRAP_USER_ID,
  DEVELOPMENT_BOOTSTRAP_USER_NAME,
  DEVELOPMENT_BOOTSTRAP_USER_PASSWORD,
  DEVELOPMENT_BOOTSTRAP_USER_USERNAME,
  DEMO_TENANT_ID,
  DEMO_TENANT_ORG_ID,
  DEMO_TENANT_PHARMACIST,
  DEVELOPMENT_PHARMACIST,
  DEVELOPMENT_PLATFORM_OPERATOR,
  DEVELOPMENT_SEED_TENANT_ID,
  DEVELOPMENT_SEED_USERS,
} from "./development-seed-users.js";

export {
  DEVELOPMENT_BOOTSTRAP_ORG_ID,
  DEVELOPMENT_BOOTSTRAP_TENANT_ID,
  DEVELOPMENT_EMPI_PLACEHOLDER_TENANT_ID,
  DEVELOPMENT_ENVELOPE_ACTOR_NAMESPACE,
  DEVELOPMENT_ENVELOPE_TENANT_NAMESPACE,
  DEVELOPMENT_VISITPAD_CATALOG_TENANT_UUID,
} from "./dev-tenant-ids.js";

export const DEVELOPMENT_BOOTSTRAP_ORG_SLUG = "hospital-saarthi-dev";
export const DEVELOPMENT_BOOTSTRAP_TENANT_SLUG = "dev-hospital";

export {
  DEVELOPMENT_BOOTSTRAP_ROLE_CODE,
  DEVELOPMENT_BOOTSTRAP_ROLE_ID,
  DEVELOPMENT_BOOTSTRAP_USER_EMAIL,
  DEVELOPMENT_BOOTSTRAP_USER_ID,
  DEVELOPMENT_BOOTSTRAP_USER_NAME,
  DEVELOPMENT_BOOTSTRAP_USER_PASSWORD,
  DEVELOPMENT_BOOTSTRAP_USER_USERNAME,
  DEMO_TENANT_ID,
  DEMO_TENANT_ORG_ID,
  DEMO_TENANT_PHARMACIST,
  DEVELOPMENT_PHARMACIST,
  DEVELOPMENT_PLATFORM_OPERATOR,
  DEVELOPMENT_SEED_TENANT_ID,
  DEVELOPMENT_SEED_USERS,
};
export type { DevelopmentSeedUser, DevelopmentSeedUserPersona } from "./development-seed-users.js";
export { PLATFORM_OPERATOR_CAPABILITY_KEYS } from "./platform-operator-capability-keys.js";

export const DEVELOPMENT_BOOTSTRAP_CREDENTIALS = {
  email: DEVELOPMENT_BOOTSTRAP_USER_EMAIL,
  password: DEVELOPMENT_BOOTSTRAP_USER_PASSWORD,
} as const;

/** Off by default — use `user-management:db-migrate` (not service startup bootstrap). */
export function shouldRunPlatformDevelopmentBootstrap(): boolean {
  const explicit =
    process.env.PLATFORM_DEV_BOOTSTRAP?.trim().toLowerCase() ??
    process.env.USER_MGMT_DEV_BOOTSTRAP?.trim().toLowerCase();
  return explicit === "true";
}
