import { randomUUID } from "node:crypto";
import type {
  CareContextRef,
  EmpiClient,
  HealthRecordBundleEntry,
  M2PatientProfile,
  RecordFoundationClient,
} from "../ports.js";

/** NRCeS / NDHM profile URLs (sandbox mock bundles). */
const NDHM_PROFILES = {
  documentBundle:
    "https://nrces.in/ndhm/fhir/r4/StructureDefinition/DocumentBundle",
  healthDocumentRecord:
    "https://nrces.in/ndhm/fhir/r4/StructureDefinition/HealthDocumentRecord",
} as const;

const ABHA_IDENTIFIER_SYSTEM = "https://healthid.ndhm.gov.in";
const SNOMED_SYSTEM = "http://snomed.info/sct";
const V3_ACT_CODE_SYSTEM = "http://terminology.hl7.org/CodeSystem/v3-ActCode";

/** Dev-only mocks when EMPI/RF are not running (see `ABDM_M2_MOCK_PLATFORM=true`). */
export class MockEmpiClient implements EmpiClient {
  constructor(
    private readonly defaultAbhaAddress = "test.user@sbx",
    private readonly patientId = "00000000-0000-4000-8000-000000000001",
  ) {}

  async findPatientByAbhaAddress(input: {
    iqTenantId: string;
    abhaAddress: string;
  }): Promise<{ patientId: string; demographics: Record<string, unknown> } | null> {
    const addr = input.abhaAddress.trim().toLowerCase();
    if (!addr) return null;
    return {
      patientId: this.patientId,
      demographics: {
        abhaAddress: addr || this.defaultAbhaAddress,
        displayName: "M2 Mock Patient",
      },
    };
  }

  async findPatientByDemographics(): Promise<null> {
    return null;
  }

  async findPatientByAbhaNumber(): Promise<null> {
    return null;
  }

  async findAbhaAddressByPatientId(input: {
    patientId: string;
  }): Promise<string | null> {
    if (input.patientId === this.patientId) {
      return this.defaultAbhaAddress;
    }
    return null;
  }

  async findM2PatientProfile(input: {
    patientId: string;
  }): Promise<M2PatientProfile | null> {
    if (input.patientId !== this.patientId) return null;
    return {
      abhaAddress: this.defaultAbhaAddress,
      patientName: "M2 Mock Patient",
      gender: "M",
      yearOfBirth: 1990,
      phoneNo: "9999999999",
    };
  }
}

function buildMockHealthDocumentBundle(opts: {
  abhaAddress: string;
  careContextReference: string;
}): HealthRecordBundleEntry {
  const ts = new Date().toISOString();
  const compositionId = randomUUID();
  const patientUrn = randomUUID();
  const practitionerId = randomUUID();
  const encounterId = randomUUID();
  const documentRefId = randomUUID();

  const placeholderBase64 = Buffer.from(
    "Mock health document generated by integration-hub for sandbox testing.",
    "utf8",
  ).toString("base64");

  const bundle = {
    resourceType: "Bundle",
    id: `MockHealthDocumentRecord-${opts.careContextReference}`,
    meta: {
      versionId: "1",
      lastUpdated: ts,
      profile: [NDHM_PROFILES.documentBundle],
    },
    type: "document",
    timestamp: ts,
    entry: [
      {
        fullUrl: `urn:uuid:${compositionId}`,
        resource: {
          resourceType: "Composition",
          id: compositionId,
          meta: {
            profile: [NDHM_PROFILES.healthDocumentRecord],
          },
          status: "final",
          type: {
            coding: [
              {
                system: SNOMED_SYSTEM,
                code: "419891008",
                display: "Record artifact",
              },
            ],
            text: "Record artifact",
          },
          subject: { reference: `urn:uuid:${patientUrn}`, display: "M2 Mock Patient" },
          encounter: { reference: `urn:uuid:${encounterId}`, display: "Encounter" },
          date: ts,
          author: [
            { reference: `urn:uuid:${practitionerId}`, display: "Mock Practitioner" },
          ],
          title: "Mock health document",
          section: [
            {
              title: "Mock health document",
              entry: [
                { reference: `urn:uuid:${documentRefId}`, display: "DocumentReference" },
              ],
            },
          ],
        },
      },
      {
        fullUrl: `urn:uuid:${patientUrn}`,
        resource: {
          resourceType: "Patient",
          id: patientUrn,
          identifier: [
            {
              system: ABHA_IDENTIFIER_SYSTEM,
              value: opts.abhaAddress,
            },
          ],
          name: [{ text: "M2 Mock Patient" }],
          gender: "unknown",
        },
      },
      {
        fullUrl: `urn:uuid:${practitionerId}`,
        resource: {
          resourceType: "Practitioner",
          id: practitionerId,
          name: [{ text: "Mock Practitioner" }],
        },
      },
      {
        fullUrl: `urn:uuid:${encounterId}`,
        resource: {
          resourceType: "Encounter",
          id: encounterId,
          status: "finished",
          class: {
            system: V3_ACT_CODE_SYSTEM,
            code: "AMB",
            display: "ambulatory",
          },
          subject: { reference: `urn:uuid:${patientUrn}`, display: "Patient" },
          period: { start: ts },
        },
      },
      {
        fullUrl: `urn:uuid:${documentRefId}`,
        resource: {
          resourceType: "DocumentReference",
          id: documentRefId,
          status: "current",
          docStatus: "final",
          type: { text: "Mock health document" },
          subject: { reference: `urn:uuid:${patientUrn}`, display: "Patient" },
          content: [
            {
              attachment: {
                contentType: "text/plain",
                language: "en-IN",
                data: placeholderBase64,
                title: "Mock health document",
                creation: ts,
              },
            },
          ],
        },
      },
    ],
  };

  return {
    careContextReference: opts.careContextReference,
    media: "application/fhir+json",
    contentJson: JSON.stringify(bundle),
  };
}

export class MockRecordFoundationClient implements RecordFoundationClient {
  constructor(private readonly defaultAbhaAddress = "test.user@sbx") {}

  private readonly contextsByPatient = new Map<string, CareContextRef[]>();

  seedCareContexts(input: {
    iqTenantId: string;
    patientId: string;
    contexts: Array<{ referenceNumber: string; display: string; hiType: string }>;
  }): void {
    const key = `${input.iqTenantId}:${input.patientId}`;
    const existing = this.contextsByPatient.get(key) ?? [];
    const byRef = new Map(existing.map((c) => [c.referenceNumber, c]));
    for (const ctx of input.contexts) {
      byRef.set(ctx.referenceNumber, {
        id: ctx.referenceNumber,
        referenceNumber: ctx.referenceNumber,
        display: ctx.display,
        hiType: ctx.hiType,
      });
    }
    this.contextsByPatient.set(key, [...byRef.values()]);
  }

  async listCareContexts(input: {
    iqTenantId: string;
    patientId: string;
  }): Promise<CareContextRef[]> {
    return [...(this.contextsByPatient.get(`${input.iqTenantId}:${input.patientId}`) ?? [])];
  }

  async listBundles(input: {
    iqTenantId: string;
    careContextId: string;
  }): Promise<HealthRecordBundleEntry[]> {
    return [
      buildMockHealthDocumentBundle({
        abhaAddress: this.defaultAbhaAddress,
        careContextReference: input.careContextId,
      }),
    ];
  }
}
